### ISSUE TITLE
Multiline TextBox defaults to a different font from a single line TextBox

### ISSUE THREAD

**Issue by paulatdunedin** [lawsie/guizero#173]
If I change a single line TextBox to multiline and specify the height, the new TextBox defaults to a different font so changes its width on screen. I can use a tk method to fix this but it's fiddly.

**Comment by martinohanlon** [comment]
you mean like this:

![image](https://user-images.githubusercontent.com/2329501/38793513-86501d60-4149-11e8-863b-46f805eee1d4.png)

guizero doesnt do anything with the fonts when creating these components, tkinter must be setting the fonts either according to its own defaults or more likely based on an operating system settings.

On my Windows 10 pc, it uses `Segoe UI` for a single line and `Courier New` for a multi-line. On a Raspberry Pi it uses `Verdana` and `Liberation Mono`.

My instinct says to not change this, mainly because I am faced with the question "what would I change it too?", any choice is bound to be the wrong one!

I will leave the issue open for the moment and see if there is any other occurrences.

You dont have to use tkinter to change the font though, you can use the `TextBox.font` property. e.g:

```python
from guizero import App, TextBox

app = App()

textbox = TextBox(app, text="text box")
ml_textbox = TextBox(app, multiline=True, height=5, text = "multiline\ntext box")

# change fonts to be one you like
textbox.font = "arial"
ml_textbox.font = "arial"

app.display()
```

or you could change 1 text box to have the same font as another, e.g. 

```python
ml_textbox.font = textbox.font
```

**Comment by martinohanlon** [comment]
I also noticed that on Windows the font size is also different between single line and multi-line text boxes, although on Raspbian its the same! 

This leads me to think this is an operating system setting.

If you wanted to change the size to be consistent you could use the `TextBox.text_size property` e.g.

```python
textbox.text_size = 10
```

**Comment by paulatdunedin** [comment]
Probably best not to try to fix this if it's the way the underlying tkinter behaves.
Thanks for the extra info. I missed the simpler ways of changing the font and text_size.

**Comment by Akuli** [comment]
The correct code would be like this in tkinter:

```python
textwidget['font'] = entry['font']
```

where `textwidget` is a `tkinter.Text` widget for multiline texts, and `entry` is a `tkinter.Entry`. This sets the font family and size.

**Comment by martinohanlon** [comment]
I dont think changes this is the right thing to do, so I can going to close the issue.

However... In 0.5.1 (not released yet), you can set the `font` and `text_size` for the "container" (App, Box, Window, etc) and its cascaded to all the widgets which belong to it... so if you set the font for the App it will be consistent for all widgets.

```python
a = App()
a.font = "Times New Roman"
t = TextBox(a)
t = TextBox(a, multiline=True)
a.display()
```
