### ISSUE TITLE
No way to assign self?

### ISSUE THREAD

**Issue by kylewetton** [lawsie/guizero#183]
Hey guys, I'm very sorry if this is the wrong place to speak about this. Please point me in the right direction and delete this issue if its not, I'm not sure if guizero supports "self" though (I also have very little experience with Tkinker)

I do have a simple script, and I'm stumped as to how to achieve this

Heres a quick and dirty script to illustrate what I need to do

```
...

def printer(value):
           print(value)
           button.destroy() #this is where I need "self", to destroy the button that was clicked

colors = ["red", "green", "blue", "purple"]
i = 0
while i < len(colors):
    color = colors[i]
    button = PushButton(app, text=color command=lambda color=color : printer(color)  )
    i += 1

```

So, basically because the variable button is not unique to each button that is rendered, I'm having a hard time referencing the actual one that was clicked. Any help would be epic.

Cheers,
Kyle

**Comment by martinohanlon** [comment]
Hi Kyle,

The use of `self` in this context isn't really what `self` is for, `self` is used internally within a Class to get a reference to an object.

There are several ways of achieving what you want to do.

The root cause of your problem is that you need construct a way of linking each element in the List `colors` to a PushButton object.

You "could" use a dictionary to keep track your PushButton objects. e.g.

```python
def printer(value):
           print(value)
           buttons[value].destroy() #this is where I need "self", to destroy the button that was clicked

colors = ["red", "green", "blue", "purple"]
buttons = {}
i = 0
while i < len(colors):
    color = colors[i]
    buttons[color] = PushButton(app, text=color command=lambda color=color : printer(color)  )
    i += 1
```
_I havent tested this code, but Im sure you get the idea_

This is only 1 way of solving the problem, there are LOTS of others.

You might find the Python section on the raspberrypi.org forum a good place to get support and get support from a larger group, there are only a couple of people who monitor guizero issues.

Martin

**Comment by martinohanlon** [comment]
Just noticed.

I would recommend using `button.hide()` rather than `button.destroy()`, once you destroy a widget you can no longer use it again - unless of course this is what you want!
