### ISSUE TITLE
_default is never updated after combo.clear() is called

### ISSUE THREAD

**Issue by MrYsLab** [lawsie/guizero#206]
I have 2 examples shown below which create a combo widget, clears out its contents and then rebuilds the combo's contents. After doing so, calling select_default() fails because _default was never restored from the original value when the combo was originally inited.

Here is the warning output:
```
------------------------------------------------------------
*** GUIZERO WARNING ***
[Combo] object with options  ['4', '5', '6']
Unable to select default option as doesnt exists in Combo
------------------------------------------------------------
```

Before pressing the button:
![screenshot from 2018-07-15 16-11-23](https://user-images.githubusercontent.com/5189838/42737968-ec72800a-8849-11e8-8ea9-21fbca7ba24b.png)

After pressing the button:
![screenshot from 2018-07-15 16-11-58](https://user-images.githubusercontent.com/5189838/42737973-faf32738-8849-11e8-8956-10691d41f8d2.png)

Example 1:
```
from guizero import App, Combo, PushButton


class ComboBug:
    def __init__(self):
        app = App(title="Hello world")
        self.items1 = ['1', '2', '3']
        self.items2 = ['4', '5', '6']

        self.the_combo = Combo(app, options=self.items1)
        self.the_button = PushButton(app, text='Push Me', command=self.switch_items)

        app.display()

    def switch_items(self):
        self.the_combo.clear()
        count = 0
        for item in self.items2:
            self.the_combo.insert(count, item)
            count += 1
        self.the_combo.select_default()


ComboBug()
```
Example 2:
```
from guizero import App, Combo, PushButton


class ComboBug2:
    def __init__(self):
        app = App(title="Hello world")
        self.items1 = ['1', '2', '3']
        self.items2 = ['4', '5', '6']

        self.the_combo = Combo(app, options=self.items1)
        self.the_button = PushButton(app, text='Push Me', command=self.switch_items)

        app.display()

    def switch_items(self):
        self.the_combo.clear()
        for item in self.items2:
            self.the_combo.append(item)
        self.the_combo.select_default()


ComboBug2()

```

**Comment by martinohanlon** [comment]
Ok, there is an interesting question here about what Combo should do.

So the scenario is this:
1. user creates a Combo but doesnt set a default (using the `selected` param on init)
1. guizero defaults the `default` to the first item in the Combo
1. when the first item is remove from the Combo, the default isnt updated.

So should the default become:
1. Always the first item in the list? (if there is one)
2. None - i.e. because the default which was created at `init` no longer exists.

This decision should also take into account what happens if the user does provide a `selected` param at init. Should the default remain the same if the option is removed? Should it revert to the first time in the list? Should it revert to None?

I favour:
1. if no `selected` option is provided the default is always the first in the list.
1. if a `selected` option is provided the default is always what it was when it was created.

**Comment by martinohanlon** [comment]
in 0.5.3

**Comment by MrYsLab** [comment]
I agree with #1, but have a question about #2. If I've selected an option at widget creation,  but then called clear(), and replaced all the options with new ones, the original selected option no longer exists, so would it make sense to first check if the original selected option still exists and if so, choose that, but if it doesn't, choose the first new option?

I have no idea how complicated what I am proposing might be, so I am not trying to create make work for you.

**Comment by MrYsLab** [comment]
Ok, I would prefer to go with whatever you are most comfortable with. Thanks. I am not sure if want me to close this or not, just close it or let me know and I will do it. Thanks.
