### ISSUE TITLE
Tests are not cross-platform (Windows fonts)

### ISSUE THREAD

**Issue by knowledgejunkie** [lawsie/guizero#230]
Several tests in the test suite are making assertions about specific Windows fonts (Times New Roman, Arial) being available locally.

During testing on Debian GNU/Linux I'm seeing 14/237 test failures due to this. Packaging guizero for Debian simply means patching out these specific tests in order to get the test suite to pass, but I'm wondering if more platform-neutral tests could be used instead?

**Comment by martinohanlon** [comment]
I thought finding a font which existed on Windows, macOS, Ubuntu and Raspbian would be simple...  It turns out I was wrong!

Regardless I have made changes (albeit a bit hacky atm) to the tests so they check for the appropriate "alternate" font on Ubuntu. I dont have a debian image to test on at hand, but it should be fine.

The changes are in the `dev` branch. I'll merge into master with the next release although Im happy to push into master now if that would of help?

**Comment by pzahemszky** [comment]
I have the same issue on macOS 10.14.6, and pull request #233 didn't fix it for me.

```
$ pytest test_text.py::test_default_values
```
```
platform darwin -- Python 3.6.5, pytest-5.3.0, py-1.7.0, pluggy-0.12.0
```
```
=============================== FAILURES ================================
__________________________ test_default_values __________________________

    def test_default_values():
        a = App()
        t = Text(a)
        assert t.master == a
        assert t.grid == None
        assert t.align == None
        assert t.size == 12
        assert t.text_color == "black"
>       assert (t.font == "Arial" or t.font == "Nimbus Sans L")
E       AssertionError: assert ('Helvetica' == 'Arial'
E         - Helvetica
E         + Arial or 'Helvetica' == 'Nimbus Sans L'
E         - Helvetica
E         + Nimbus Sans L)

test_text.py:29: AssertionError
```
