### ISSUE TITLE
.value properties for widgets

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#25]
How do you feel about creating .value getter and setter properties for the widgets?

e.g. 

a value property would allow CheckBox value to be get and set as a boolean

```
class CheckBox(CheckButton):

    @property
    def value(self):
        return (self.get_value() == 1)

    @value.setter
    def value(self, value):
        if value:
            self.select()
        else:
            self.deselect()

check = CheckBox()
if check.value:
    check.value = False
    
```

The same value property could be created for all widgets allowing a simple interface to get and set its value.

**Comment by bennuttall** [comment]
:+1: to this. The values of GUI objects are not uniform and really hard to work out how to get to. If they had a standard value property you could get and set (like Martin shows) it would be much easier. Some use standard `get()` and `set()` methods, which is ok, but they don't all do that.

I can see from the docs how to read the value of a checkbox using `get_value()`, but not how to set it, and I'm struggling to see how to do that. I remember I've done this before and find in [some old code](https://gist.github.com/bennuttall/e8075517e548e213a967bccc47dfd4e5#file-pinsgui-py-L19) that there's `.value.get()` and `.value.set()`...

**Comment by lawsie** [comment]
I didn't know you could do this, so thanks for teaching me another thing Martin!

**Comment by lawsie** [comment]
Just thinking about this. I think it's a really good idea and I would have done this in the first place had I known. However, if I remove the `get_value()` etc. methods that already exist, this will break some existing programs people have written. I don't want to annoy people who might be using guizero for (for example) controlled assessment. Eek! I suppose they could always use the previous release version? Any thoughts @martinohanlon or @bennuttall ?

**Comment by bennuttall** [comment]
The general rule is the API is considered unstable until the release of v1.0. You have broken BC before (with alignment arguments), and I think most of the stuff that would be removed is advanced stuff that's not documented in the guizero docs anyway.

However, I think this issue is purely suggesting you *add* `.value` properties, not to take away the existing ones, which would be moved elsewhere by my suggestion in #38.

We have generally aimed to not break BC in gpiozero, but we have (just) when necessary, and only for advanced usage, like pin objects and pin factories. It's worth doing it if there's more to be gained. And you can always give people plenty of notice, and document the fact it's changed! We use sphynx for docs so we have docs for every version available.

**Comment by martinohanlon** [comment]
I would agree with @bennuttall even though you can consider your API to be unstable until v1 I would just keep the existing methods.

**Comment by ukBaz** [comment]
I have seen libraries support the old and new API side by side for a couple of releases to gently aid the switch to the new API. If someone calls one of the old functions then you show a warning message indicating that it is deprecated.

A slightly tongue-in-cheek benefit to doing breaking API changes is that you hear from users you didn't even know were using your library  :-)

**Comment by lawsie** [comment]
I have another question. Supposing I want to set a property called "color" for a particular widget. If there is already a method called `color()` - either defined by me or in the underlying tk object - I can't make a property with the same name, right? Is there any way of overriding this? 

For example, in the `Tk` object, there is a method called `title()` defined. This means I can't add something like 

```python
@property
    def title(self):
        return self.title()
```

... because I'm relying on the `title()` method to get me the title, but creating the property also called `title` creates an infinite recursion. 

So is it not possible to have `app.title = "Nice title"`, or is there a way of overriding this somehow. (At this stage, `App` extends `Tk`)

**Comment by bennuttall** [comment]
That's right. A property or method is still just an attribute, whether it's callable or not. It still exists in that particular namespace.

If you bung all the tk stuff under `obj.tk` as suggested in #38 then you can choose what you expose at the top level, so `title` could be a property rather than a method, and you wouldn't need both.

**Comment by lawsie** [comment]
Yeah I'm intending to do that, but if I also want to keep the old methods so that it doesn't break the API for people, that causes a bit of a pain in some places! :(

**Comment by DavidWhaleMEF** [comment]
This is all about formally managing the deprecation process of your API methods in a controlled manner, and there are ways and means to do that. 

The problem with saying 'they can always use an older version of the API' is that they are bound to want the shiny new features anyway even if on the old API, but probably won't have the skills or time to do a massive merge to get those new features retro-fitted, or won't have the time to update their existing homework to the new style.

You can use some __getattr__ magic to delegate to the new inner tk, and make that delegation optional. __getattr__ is only called if the class does not already have that method/attribute defined in it's attribute dictionary.

In early releases, leave deprecated methods enabled by default. In later releases, disable deprecated by default. That way you can use both styles interchangeably, but the day that you flip the default ENABLE_DEPRECATED to False, the user can still set it to True at runtime if they want to use the old way. Here is a general design pattern for that. 

It gives your users a way to migrate gradually, without breaking old code (or if you do break old code, users can easily flip the switch to fix it).

```
class MyClass():
    ENABLE_DEPRECATED = True

    def __getattr__(self, name):
        if ENABLE_DEPRECATED and hasattr(self.tk, name):
            print("warning: Using deprecated method:%s" % str(name))
            return getattr(self.tk, name)
        else:
            raise AttributeError("No such attribute:%s" % str(name))
```

c = MyClass()
c.old_method() # works
c.ENABLE_DEPRECATED = False
c.old_method() # get error
```

**Comment by lawsie** [comment]
Added these to 0.4 where they make sense, but maintained backwards compatibility.
