### ISSUE TITLE
Background colour for MenuBar

### ISSUE THREAD

**Issue by PilleniusMC** [lawsie/guizero#263]
It would be really nice if you could set the background colour of the MenuBar, as this is currently not in guizero by default, though you could work around that by going through tkinter.

**Comment by martinohanlon** [comment]
I have been doing some investigation into this...

It is dependant on the operation system (or more accurately the window manager) whether you are able to set the background colour of the menu_bar.

Using the existing `bg` property on `MenuBar` you are able to colour the bar in Linux (gnome) - as per this example from Raspbian.

![image](https://user-images.githubusercontent.com/2329501/54643585-34e96300-4a8f-11e9-8347-f03dcf897729.png)

However setting the `bg` in Windows (or macOS) has no effect.

![image](https://user-images.githubusercontent.com/2329501/54643652-55b1b880-4a8f-11e9-9fd0-beeb6edf09ca.png)

Regardless of this a change which should be made is to also colour the individual menu "sub menus" so that when using window managers which do support changing the `bg` they match.

**Comment by martinohanlon** [comment]
I have made the change, so at least the sub menus are "colored".

![image](https://user-images.githubusercontent.com/2329501/54644521-6105e380-4a91-11e9-88d2-c2e353773622.png)

**Comment by PilleniusMC** [comment]
So sadly it isn't really something you can easily do. Oh well. It was just an idea.

**Comment by martinohanlon** [comment]
@PilleniusMC - its something you cant do at all (at least if you are using Windows or macOS)

**Comment by martinohanlon** [comment]
Change to set sub menu `bg` colour is in dev.

**Comment by lawsie** [comment]
I think this is confusing and I'm not sure we should add it. If a learner tries to change the background colour but they are on Windows/Mac (pretty likely in a school) then it won't work and they might not understand why. Is this an edge case we could consider leaving for more advanced users to do via tk, given it only works on linux?

**Comment by martinohanlon** [comment]
Changing `bg` on MenuBar is already in guizero and I think leaving it "as is" is more confusing for Windows and macOS users.

**As-Is**

Using `menubar.bg = "red"` on Windows and macOS will have no result, leaving people confused - "why hasnt my code worked?".

![image](https://user-images.githubusercontent.com/2329501/54668993-2bd8b000-4ae8-11e9-8ac6-8e49b4bd55df.png)

**To-Be**

If we implement this change, at least the sub-menu's of the MenuBar on Windows and macOS will have changed.

![image](https://user-images.githubusercontent.com/2329501/54669110-72c6a580-4ae8-11e9-9de0-c7a941b89381.png)

^ this has the added benefit in Linux that the "whole" of the menu's `bg` is changed.

We should certainly put a note in the documentation regarding `bg` use. I suppose there is also the option of putting in a warning if setting `bg` when using Windows or macOS, although I think this will become annoying.

**Comment by martinohanlon** [comment]
Released in `0.6.2`
