### ISSUE TITLE
Clearing a TextBox

### ISSUE THREAD

**Issue by Piece-of-pi** [lawsie/guizero#27]
I have followed the documentation for using a TextBox and I have used the following code to use a TextBox to test if the text box is working:

```
from guizero import App, TextBox, PushButton, Text

app = App()

def save_code():
    stuff = input_box.get()
    print(stuff)
    input_box.clear()
    text = Text(app, text = "It is working!")

input_box = TextBox(app, text = "Type here")

button = PushButton(app, command = save_code)
button.set_text("Save")

app.display()
```

When I click the button I get the following message:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1536, in __call__
    return self.func(*args)
  File "/home/pi/Python/text_box.py", line 6, in save_code
    input_box.clear()
  File "/usr/local/lib/python3.4/dist-packages/guizero/TextBox.py", line 31, in clear
    self.delete(0, END)
NameError: name 'END' is not defined
```

This error message gives me the impression that GUI Zero is at fault. 

Edit - I have removed the `input_box.clear()` bit in my code and it all works perfectly. However, whatever I try the TextBox won't clear!

**Comment by DavidWhaleMEF** [comment]
I suspect this is because the Tk definition of END is not imported. The problem with wrapping a complex  library is, erm, you either have to wrap everything, or your users have to import everything.

END is defined in the tkinter module, see this for an example of how you would normally code this natively in tkinter:

http://www.python-course.eu/tkinter_text_widget.php

The 'from tkinter import *' at the top is the clue, it imports END and a billion other things that are required to make tkinter work.

**Comment by lawsie** [comment]
You're right - sorry about this. I broke the imports in a commit a while back and have not yet fixed this.
