### ISSUE TITLE
Scroll Bar w/ resize still does not work.

### ISSUE THREAD

**Issue by Pachy** [lawsie/guizero#284]
The updated version works if the width of the list box is > 220.  If it is less than 200 (or so), the scroll bar disappears, and the work around from the previous release no longer works.  Inbetween you get a progressively skinnier scroll bar.

```python
from guizero import App, Text, PushButton, Box, Window, ListBox
app = App(title="piCD", height=250)
SelList = ListBox(app, grid=[0,1], align="left", scrollbar=True)
for x in range(20):
    SelList.append(str(x))
#SelList.resize(450, 200)         # Works
#SelList.resize(100, 200)        # Scroll bar disappears
app.display()
```

edited - added code tag

**Comment by martinohanlon** [comment]
So... In summary, tk is weird, you need to make the internal listbox smaller!

This is happening because (apparently) tk maintains a "default" size of a listbox widget (10 characters) even if you tell that widget to fill the space of its container, in this case a frame which holds the listbox and the scrollbar.

If you make the container smaller than the "default" size the listbox wont go any smaller and therefore the scrollbar on the right is pushed out of the edge of the container and you can no longer see it.

The size that this happens is dependent on the font size you are using as the listbox is measured in characters.

You can fix this by setting the width of the listbox to be 0 e.g.

```python
from guizero import App, Text, PushButton, Box, Window, ListBox
app = App(title="piCD", height=250)
SelList = ListBox(app, grid=[0,1], align="left", scrollbar=True)
# set internal listbox width to be 0
SelList._listbox.tk["width"] = 0
for x in range(20):
    SelList.append(str(x))
# skinny listbox
SelList.resize(100, 200)
app.display()
```

Its a 1 line change which I will put in the next release.

**Comment by martinohanlon** [comment]
In `dev`

**Comment by martinohanlon** [comment]
in 0.6.3

**Comment by Pachy** [comment]
Thanks. Appreciate the fast response.  Verified okay.
