### ISSUE TITLE
Feature Request: Allow user to add ttk widgets

### ISSUE THREAD

**Issue by MrYsLab** [lawsie/guizero#301]
I often need ttk widgets, such as notebook. Having the ability to add ttk widgets to a guizero application would make the library more robust (IMHO).

**Comment by lawsie** [comment]
I have to say that I don't know much about ttk, but my initial feeling is that adding support for it would add a lot of complexity to guizero, both in terms of things to support and ensure they don't break when a new release is added, and in terms of scope for things you can do. (I realise you are asking for this because in your view increased scope for things you can do is a good thing!) My primary aim for guizero was and is to make it a library for beginners, where they can easily create a simple GUI without being overwhelmed by options, but equally they are not restricted from doing more complicated things if they wish. I consider the more complicated things to be outside the scope of guizero. The library has grown and become much more widely used than I ever imagined, but I hope that we can stay true to that original aim. What are your thoughts @martinohanlon ?

**Comment by martinohanlon** [comment]
You can already mix ttk widgets with guizero using the `add_tk_widget` functionality. https://lawsie.github.io/guizero/usingtk/

I tested using the Progressbar from ttk in this example and it worked. https://github.com/lawsie/guizero/blob/master/examples/tk_widget.py

I cant comment for other ttk widgets, but providing they inherit from the generic tk widget (i.e. they have a master, have .pack & .grid, etc) they should work.

**Comment by lawsie** [comment]
Then happy days! 👍

**Comment by MrYsLab** [comment]
It took a little playing but I got it to work. Thanks for the sample code. I am providing the code that I used and a couple of  screenshots. The borders around the tabs are decorated differently from a non-guizero implementation. The first screen shot is the guizero verison and the second is native ttk.  

Two questions:
    1. Is there a way for me to affect the look of the tabs in guizero? If not, I can live with what is there.
    2. I want to add space above and to the left of the notebook.  Would the best way be to add empty boxes above and to the left of the notebook?

```
from guizero import App, Box
from tkinter import ttk
from tkinter.ttk import Notebook

# set up app to use grid layout
app = App(title="Using ttk Notebook", layout="grid")

# set up box to use grid and place it in app at 0,0
box = Box(app, border=True, layout='grid', grid=[0,0])

# create a notebook
nb = Notebook(box.tk)

# create some frames for the tabs
signal_page_inputs = ttk.Frame(nb)
signal_page_outputs = ttk.Frame(nb)

# add the tabs
nb.add(signal_page_inputs, text='Signal Inputs')
nb.add(signal_page_outputs, text='Signal Outputs')

# important - add tk widget only after it is completed
box.add_tk_widget(nb, grid=[0,0])


app.display()

```
And here is what it looks like:

![Screenshot from 2019-05-21 09-48-44](https://user-images.githubusercontent.com/5189838/58101456-ae93ef00-7bad-11e9-941a-85654d09c058.png)

![Screenshot from 2019-05-21 09-51-33](https://user-images.githubusercontent.com/5189838/58102012-983a6300-7bae-11e9-990d-80faa7b8aba6.png)

Thanks for the quick responses.

**Comment by martinohanlon** [comment]
Im not sure what you mean about the look being different in guizero.

Is it just because you have put a border on the Box in guizero?

There are probably several ways of putting a pad around the top and left, I would tend to just use 2 boxes, one aligned to the top which fills the width and another aligned to the left which fills the height. You can find more information about using layouts here https://lawsie.github.io/guizero/layout/

**Comment by martinohanlon** [comment]
I modified your code to use aligns rather than grids for the layout and added a 10 pixel Box to the top and left to pad it.

```python
from guizero import App, Box
from tkinter import ttk
from tkinter.ttk import Notebook

# set up app to use grid layout
app = App(title="Using ttk Notebook")

# set up box to use grid and place it in app at 0,0
pad_left = Box(app, align="left", width=10, height="fill")
pad_top = Box(app, align="top", width="fill", height=10)
box = Box(app, align="top", width="fill")

# create a notebook
nb = Notebook(box.tk)

# create some frames for the tabs
signal_page_inputs = ttk.Frame(nb)
signal_page_outputs = ttk.Frame(nb)

# add the tabs
nb.add(signal_page_inputs, text='Signal Inputs')
nb.add(signal_page_outputs, text='Signal Outputs')

# important - add tk widget only after it is completed
box.add_tk_widget(nb, align="left")

app.display()
```

I am going to close this issue as the feature is not needed.

**Comment by MrYsLab** [comment]
Thanks. I figured out the difference in the look of the tabs. I did not give the tab page a height value and therefore was seeing the bottom margin of the notbook.
