### ISSUE TITLE
box color and size

### ISSUE THREAD

**Issue by Pachy** [lawsie/guizero#319]
In version 1 the text_size and text_color methods only work if they are executed after Text items are added to the box.  In previous versions you could execute these methods beforehand and it worked just fine.  Is there a purpose, or is this an error?  I hate to have to change all my code unless there is a purpose.

```python
from guizero import App, Text, PushButton, Box, Window, ListBox
app = App(title="piCD", height=250)
DataBox = Box(app, layout="grid", width="fill", align="top", 	border=False)
DataBox.text_size = 30
DataBox.text_color = "red"
Text(DataBox, grid=[0,0],  align="left", text="Hi There")
Text(DataBox, grid=[1,0],  align="left", text="  Brave New World")		# no longer works
app.display()
```

edited to format code

**Comment by martinohanlon** [comment]
This is "by design", however that is not to say I particularly like it...

The change is as a result of fixing this issue https://github.com/lawsie/guizero/issues/290 and it comes down to the Text widget having "non-standard" defaults when it is initialised. The issue above goes into a lot more detail.

To get your `Text` widgets to inherit from your `Box` you will have to explicitly state that they should be created with no default for `size` and `color` by setting them to `None`. e.g.

```python
Text(DataBox, grid=[0,0],  align="left", text="Hi There", color=None, size=None)
```

**Comment by martinohanlon** [comment]
I think we can fix this. I came across this in tkinter. http://effbot.org/zone/tkinter-option-database.htm You can change the default behaviour of widgets in the option database. Using this we should be able to modify the default behaviour of a tk Label.

I did some experiments in the text-inherit branch.

**Comment by martinohanlon** [comment]
Prepared a change so that Text works the same as other widgets when dealing with defaults. 

The code is in https://github.com/lawsie/guizero/tree/text-default .

Commit is here - https://github.com/lawsie/guizero/commit/42f335114016e7735586bdc3310a10ff5f873840

I need to do some x platform testing, but Im feeling pretty confident.

The change would also allow a user to modify the defaults via tk_options property in system_config

e.g. this would set the default background colour of all Buttons to be green.

```python
from guizero import system_config
system_config.tk_options["*Button.Background"] = "green"
```

**Comment by martinohanlon** [comment]
Tested on Windows, macOS and Raspbian. All seems good.

Im going to merge into dev for inclusion in the next release.

**Comment by martinohanlon** [comment]
in v1.1.0
