### ISSUE TITLE
Pop-ups

### ISSUE THREAD

**Issue by Bernd54Albrecht** [lawsie/guizero#331]
Example code for Pop-ups does not work under Raspbian!
Error message:  'App' object has no attribute 'info'    or warn etc 
remedy:
from guizero import App, info, warn, yesno
 
and then:   info("text1","text2")    without preceding  app.

**Comment by martinohanlon** [comment]
Can you confirm what version of guizero you are using.

```python
import guizero
print(guizero.__version__)
```

I suspect you need to upgrade.

```
sudo pip3 install guizero --upgrade
```

**Comment by martinohanlon** [comment]
Confirm the example code works on Raspbian

```python
from guizero import App
app = App(title="Biscuit monitor")
app.warn("Uh oh!", "You are almost out of biscuits!")
app.display()
```

![image](https://user-images.githubusercontent.com/2329501/63125225-0a032c80-bfa5-11e9-99f8-63cbc07de036.png)

Default version installed with Buster is an older version and needs to be upgraded. Run.

```
sudo pip3 install guizero --upgrade
```

If you get `AttributeError: module 'guizero' has no attribute '__version__'` when trying to check version, its because the version is really old.

Closing

**Comment by Bernd54Albrecht** [comment]
Thanks for your swift response. Yes, it works after the upgrade.
I thought, I was up-to-date with my brand-new Pi 4 and latest Raspbian.
Maybe, you could advertise this upgrade, because it is obviously not part
of   sudo apt-get upgrade.

After the course I walk through the online documentation step by step. May
take a while, and then I will come up with my conclusion.

Mom to daughter: What did you learn today in school?
Daughter: Not enough. They told me to come back tomorrow.

Greetings
Bernd (Bernd54Albrecht)

Am Do., 15. Aug. 2019 um 22:23 Uhr schrieb martinohanlon <
notifications@github.com>:
