### ISSUE TITLE
modal win is useless in Raspberry

### ISSUE THREAD

**Issue by Richard0610** [lawsie/guizero#364]
**Describe the bug**
modal win is useless in Raspberry

**To Reproduce**
1.make a small program

from guizero import App, Window

app = App()
app.set_full_screen()
win = Window(app, title='modal')
win.show(True)
app.display()

2.run it, then click the outside window

3.the modal window will hide
the problem occur in Raspberry

**System information:**
 - OS: Raspbian GNU/Linux 10 (buster)
 - guizero version: 1.1.0

**Comment by Richard0610** [comment]
win.tk.grab_set_global()
it will help
please arrange into code, tks :)

**Comment by martinohanlon** [comment]
Thanks for the positive vibes .

I haven't tested but it looks like you are expecting like the modal window to hold complete context of the desktop.

By setting the App and full screen you are overriding the default behaviour of the desktop. 

When you click off the modal window the context is given back to the desktop, but you have covered the desktop in the full screen app, so you see the app again.

By using 'grab_set_global' it would redirect ALL events to this widget. No other applications on the desktop (guizero or otherwise) would work until this modal window was closed.

This is a use case specific to your requirements I suggest you use the tk extensions e.g. win.tk.set_grab_global to do this for your app.

**Comment by Richard0610** [comment]
》 it looks like you are expecting the modal window to hold complete context of the desktop.
actually, I want an OEM dialog.
the dialog works well ( yesno, info, etc...), so if there's code about dialog, maybe I can learn how to  fix it.

for the issue "No other applications on the desktop (guizero or otherwise) would work"
I try to understand but.. how to test it?
okok, I understand now :)

so it really can't do this if we want multi-task on all system.
I had workaround by some skill
for example: <focus out>
bind a function when the win focus out, then bring it to top.(I can't find the API, are there?)
so my last version is destory old then gen a new one  XDDDD
it seems dirty code but works XDDDDD

**Comment by Richard0610** [comment]
>  if there's code about dialog
yes,there is.
but it's too hard too deep for me...
