### ISSUE TITLE
Incompatibility with Matplotlib

### ISSUE THREAD

**Issue by PYBurosse** [lawsie/guizero#439]
So this is probably a stretch, and not something that's gonna happend to a lot a people. I'm using both guyzero and matplotlib for a project. My code basically opens a guizero window to choose a sensor to connect to, then a matplotlib graph that displays live data from that sensor. There a button on the graph that opens a new guyzero window that I want to use to send settings to the sensor. This window just contain Texts and TextBoxes. The TextBoxes are supposed to be prefilled with the sensor current parameters.

The problem I have is that the prefilled text won't appear in the TextBoxes.

Here is a sample code I made that still has this issue (I know that in that code, I never call `plt.show()`. If I do, the bug doesn't appear. Just know that in my actual code, both the graph and the second guizero window exist at the same time. But the same bug appears in either case, so...)

```
import matplotlib.pyplot as plt
from guizero import App, Text, ListBox, PushButton, TextBox

sensor = None
sensorid = None
def select_sensor():
    global sensor
    sensor = listbox.value
    app.destroy()
app = App(height=200, width=150, title="Sensor")
app._on_close = exit
text = Text(app, text="Pick a sensor")
listbox = ListBox(app, items=["a","b","c"], height=70, width=40)
selectButton = PushButton(app, text="Ok", command=select_sensor)

app.display()

plt.plot([0,1,2,3], [4,1,2,5])
#plt.show()

settingWindow = App(height=300, title="Settings")
textbox= TextBox(settingWindow, text="This text won't appear")
settingWindow.display()
```

**System information:**
Windows 11
Python 3.10.2
guyzero 1.3.0

**Comment by martinohanlon** [comment]
I haven't tried your program but I strongly suspect this issue is because you are essentially running 2 tkinter applications in the same program.

guizero and matplotlib both use tkinter and you can only have 1 main tkinter application running.

This article describes how to embed matplotlib graphs into tkinter applications (it might help). https://www.geeksforgeeks.org/how-to-embed-matplotlib-charts-in-tkinter-gui/

I don't believe this is a bug with guizero so I am going to remove the label but I will leave it open until the next release / issue review.

**Comment by Ross-TheBoss** [comment]
I have an example of how to embed a matplotlib graph into a guizero application:
```python
from guizero import App, Box, Text

import matplotlib.pyplot as plt

from matplotlib.backends.backend_tkagg import (FigureCanvasTkAgg,
NavigationToolbar2Tk)
# Implement the default Matplotlib key bindings.
from matplotlib.backend_bases import key_press_handler

# Create graph
ages = [23, 25, 26, 27, 28,
        29, 30, 31, 32, 33,
        34, 35]

salaries = [22960, 25129, 26443, 27434,  30453,
            31454, 34253, 35034, 34034, 35544,
            36346, 40354]

fig, ax = plt.subplots(figsize=(5, 4.4))

fig.subplots_adjust(left=0.16, bottom=0.11,
                    right=0.9, top=0.88,
                    wspace=0.2, hspace=0.2)

ax.plot(ages, salaries)

ax.set_title("Median Salary (GBP) by Age")

ax.set_xlabel("Ages")
ax.set_ylabel("Median Salary (GBP)")

# Integrating the figure into guizero.
app = App(title="Integrated Graph")

canvas_box = Box(app, border=1)

# Creating the Tkinter canvas containing the Matplotlib figure.
canvas = FigureCanvasTkAgg(fig, canvas_box.tk)
canvas.draw()

# Creating the Matplotlib toolbar
toolbar = NavigationToolbar2Tk(canvas, canvas_box.tk)
toolbar.update()

# Bind pressing a key to Matplotlib's key press event handler.
canvas.mpl_connect("key_press_event", key_press_handler)
# Add the tkinter canvas widget to a guizero Box. 
canvas_box.add_tk_widget(canvas.get_tk_widget())

def close_app():
    app.tk.quit() # Stop the tkinter mainloop
    app.destroy()

app.when_closed = close_app # same as _on_close attribute.

text1 = Text(app, "Text to prove that the integration worked")

app.display()
```
I recommend putting the matplotlib graph and toolbar into a box, since the toolbar is always packed to the bottom of the window.

The matplotlib documentation also has an example of how to embed a graph into a tkinter application, and this has some additional features such as being able to modify the graph using a slider.

https://matplotlib.org/stable/gallery/user_interfaces/embedding_in_tk_sgskip.html

**Comment by martinohanlon** [comment]
Thank you for the example @Ross-TheBoss

**Comment by martinohanlon** [comment]
Can this issue be closed?
