### ISSUE TITLE
Mention App().tk.geometry() Functionality

### ISSUE THREAD

**Issue by chaosgrimmon** [lawsie/guizero#449]
guizero's documentation doesn't explain what to do if the user wants their window in a particular location (ie. making a half-screen app, but default window placement means it doesn't align to the screen edge and is partially offscreen)

tkinter naturally does handle this, using the method named in the title, but as it stands it isn't immediately clear to a new user that it exists, nor how it would be applied in the context of guizero objects.

If someone really wanted to, they could add a wrapper to make it a legitimate feature, the same way width and height don't need to formatted using tk's geometry strings. Alternative inputs support could then potentially also automatically offer options to align based on screen-dimensions, but the key thing is that the functionality is somehow made apparent.

**Comment by martinohanlon** [comment]
> guizero's documentation doesn't explain what to do if the user wants their window in a particular location

Ok.. the documentation hardly covers any 'what to do if the user wants ...' scenarios.

This scenario seems very specific.

**Comment by lawsie** [comment]
I feel like this is a bit of a niche thing that people can work out how to do via tkinter if they want to, rather than core functionality, and so it doesn't really belong in the guizero docs. There are plenty of things from tkinter we don't wrap but you can still do if you want to, but adding too many possibilities will make it less accessible for beginners.
