### ISSUE TITLE
Update installation documentation for Raspberry Pi 'bookworm' OS

### ISSUE THREAD

**Issue by DeeJay** [lawsie/guizero#486]
**Is your feature request related to a problem? Please describe.**
The October 2023 release of RasPiOS based on Debian 12 Bookworm means that installation of guizero by means of **sudo pip3 install guizero** is no longer viable.

**Describe the solution you'd like**
Document how to use pip in single-user mode in a venv to install guizero

**Describe alternatives you've considered**
Remove reference to pip[3] and rely solely on python3-guizero debian/apt package

**Comment by bsimmo** [comment]
Though if you follow the venv setup, you'll just install into the venv.
It's all 'new' to RaspberryPi OS, so will take time.
They're also looking at some method of making venv's easy, not sure how/wheat/when.

You could also override it and install globally still.

The joys :-)

**Comment by martinohanlon** [comment]
Is `apt install python3-guizero` the right approach for guizero on linux?

A couple of years back I wouldnt have suggested it because the pace of updates to guizero far outstripped the updates to the apt package. However guizero is a much more stable package now with much slower release cycles (thats a good thing!).

I would advocate including instructions on using `apt` for linux with a note about using a venv and pip if you want the latest release.

**Comment by DeeJay** [comment]
I am just a user and 'critical friend'. I don't know what the right, supportable, answer is.

But if **apt install** is NOT the right answer for guizero on Debian Linux then it needs taking out of the current live production version of the documentation as a possible option.

_{I don't recall adding the inappropriate 'nice to have' label, but can't see how to remove it.}_

**Comment by martinohanlon** [comment]
>apt install is NOT the right answer for guizero on Debian Linux
I said I think it is the right option for Linux.

In the past (and currently) it wasnt the "suggested" option (it is noted as an alternative) because installing via `pip` was just as easy and there are benefits of always getting the latest release.

Using `pip` is now not as easy as using `apt` and the benefits have diminished.

**Comment by martinohanlon** [comment]
Ok, not further respones, I am going to update the docs to use `apt` for Raspberry Pi and give `pip` as an alternative.

**Comment by martinohanlon** [comment]
Resolved
