### ISSUE TITLE
Large digital numbers from a sensor

### ISSUE THREAD

**Issue by James100000** [lawsie/guizero#51]
I have combine two programs into one, the first  program is reading the temperature from a sensor,
the second program is guizero producing large graphics on the screen, numerals or text.
The two programs work fine separately, when combined the read out is just producing one reading it is 
not looping to read further information.

What I am trying to do is produce large digital numbers on the screen from the sensor.

Thanks
"""
`` ``  ``
from guizero import App, Text

#main loop
#while True:
tempStore = open("/sys/bus/w1/devices/28-00000781336e/w1_slave")	#change this number to the Device ID of your sensor
data = tempStore.read()
tempStore.close()
tempData = data.split("\n")[1].split(" ")[9]
temperature = float(tempData[2:])
temperature = temperature/1000
        #print(temperature)
#-------------------------------------------------------------------------------------------------------------------
def update_writing():

    T = temperature
    writing.set(T)
    app.after(200, update_writing)
app = App(height=2000, width=2000,bgcolor="black")
writing = Text(app, text="", color="red",size=110)

writing.pack(fill="none", expand=True)
app.after(200, update_writing)
app.display()

` `` `` ``

"""

**Comment by lawsie** [comment]
You can't use things like infinite loops with a GUI because the program gets stuck in the loop and will not update the GUI. What you need to do is put your code to read from the temperature sensor inside the `update_writing()` function, without a loop. So, where you currently have `T = temperature` will be your code to read from the sensor, and then you will set the value of the sensor and call the function again after 200ms using the code you already have. 

There is an example of reading from a sensor [here](https://github.com/lawsie/guizero/blob/master/examples/auto_update_example.py)
