### ISSUE TITLE
Waffle: Memory and Redrawing Pixels

### ISSUE THREAD

**Issue by scotty3785** [lawsie/guizero#54]
More a proposal for consideration rather than an issue.
This follows a discussion on Twitter with @scottofthedead1 (me), @Coding2Learn and @CodeBoom

1. Each time the colour of a pixel is changed, a new object is drawn on to the canvas over the top of the existing pixel. This seems to have an adverse behavior of the application if the pixels are changed many times. I have a fix that stores the object id of each pixel in the __init__ function and then uses the `canvas.itemconfig` method to modify the fill colour of the existing pixel rather than drawing a new one.

2. Given that I'm saving the object ids of the pixels there is no longer any need to have a separate array containing the colour of each pixel as I can query the fill of each object. With this, I'd propose getting rid of the `remember` attribute of Waffle and the `save_colors` array.

Any thoughts about how this might impact existing applications or backwards compatibility?
I have some working code that needs tidying up so can make a pull request against whichever branch.

**Comment by lawsie** [comment]
Sorry - was too exhausted last night to reply on Twitter. Thanks for this! 

If you have a look at the current state of Waffle.py on the 0.4 branch you will see that there are a number of changes, including your "clickable waffle" code. If you could pull your method against that branch, being careful to keep the other changes, that would be fab :) You'll see that I already "removed" the remember attribute because it's a bit pointless, but for the time being it needs to stay as a constructor argument for backwards compatibility, even though it will always be true. The save_colors array can be safely removed if your implementation needs that as no one should be accessing it directly. This might mean some modification of the various methods though.

I'm also planning to add a way to address the waffle object as if it were a 2D list - I have the code ready but haven't added it yet.

**Comment by lawsie** [comment]
Fixed #61
