### ISSUE TITLE
`ButtonGroup` `horizontal` argument has inverse result

### ISSUE THREAD

**Issue by Coal0** [lawsie/guizero#69]
Supplying `horizontal=True` to `ButtonGroup.__init__` makes the widgets pack below one another. `horizontal=False` (default) causes them to pack next to each other. Isn't that the opposite of what is supposed to happen? I'm kind of confused about this one. Technically, each widget gets assigned its own *horizontal* line (row), so this could be the expected behavior. Just curious.

**Comment by lawsie** [comment]
Yes, this is pretty stupid - it's because the grid layout coordinates were originally accidentally reversed. When I fixed the grid layout to work properly, I forgot to change round the parameters - ButtonGroup is actually just a bunch of buttons laid out in a frame on a grid layout! Should be fixed now.
