### ISSUE TITLE
Reading 2 Graphic readouts at the same time.

### ISSUE THREAD

**Issue by James100000** [lawsie/guizero#78]
I have had this program running for 24 hrs and not a problem.
It is showing local time and UTC time in large Graphics on the screen.
Both Graphics working independently to each other.
No problems with the ram filling up.

I tried  update writing from 200 to 1000, 2000, still did not make any difference.

When I run the same program from two temperature sensors the program runs for five minutes and stops because of memory filling up, maybe.

I have tried the "del" function to clear variables with no success also tried the "gc.collect()" function to clear unwanted data.

For sum reason this program dose not like reading the two temperature sensors or the Raspberry Pi model 2 dose not have the capacity to run a large graphics program and the temperature sensors as well.

I was just thinking now, if I independently assign each temperature sensor with its own independent read out like the program below, it might just work reading two different sensors.

Thanks

``````
import datetime

import pytz

from datetime import datetime, date, time
    
import time

from guizero import App, Text
def update_writing():
          
          
          
          
           T1 = (time.strftime("%H:%M:%S"))

           #T3 = (time.strftime("%H:%M:%S"))
           
           T3 = (datetime.utcnow().strftime("%H:%M:%S"))

           
                  
           writing.set("LOCAL TIME")

           writing1.set(T1)

           writing2.set("UTC")

           writing3.set(T3)
           
           app.after(200, update_writing)

           
           

app = App(height=1000, width=1000,bgcolor="black")





writing = Text(app, text="", color="red",size=50)

writing1 = Text(app, text="T1", color="red",size=50)

writing2 = Text(app, text="", color="red", size=50)

writing3 = Text(app, text="T3", color="red",size=50)





#writing.pack(fill="none", expand=True)

app.after(200, update_writing)

app.display()

``````

**Comment by Coal0** [comment]
We can't help you with the issue you're having if you leave out crucial information. What happens after 5 minutes? Did the problem occur only once or can it be reproduced? It looks like you left out part of the code, where do you use `pytz`?

---

From what I can tell from this snippet, there's a couple of pretty big issues with your code. I suggest you tackle these *first*, because they'll make debugging a lot easier.

* You're importing `time` from `datetime`, then importing the `time` module, which overwrites `datetime.time`. I suggest importing `datetime` 'as' `dt`:

  ```python
  import datetime as dt
  import time
  ```
  
  You will then have to prefix some objects with `dt`:

  ```python
  ...
  T3 = (dt.datetime.utcnow().strftime("%H:%M:%S"))
  ...
  ```

* You use way too much whitespace. If you use whitespace and blank lines sparsely, they can greatly improve readability:

  ```python
  import datetime as dt
  import time

  from guizero import App, Text
  import pytz


  def update_writing():
      T1 = (time.strftime("%H:%M:%S"))
      #T3 = (time.strftime("%H:%M:%S"))
      T3 = (datetime.utcnow().strftime("%H:%M:%S"))

      writing.set("LOCAL TIME")
      writing1.set(T1)
      writing2.set("UTC")
      writing3.set(T3)
           
      app.after(200, update_writing)
  ```

  * Standard library imports are grouped together; then a single blank line; then third-party library imports

  * Keep two blank lines in between top-level function definitions

  * Retrieving and formatting the current time is grouped together; then a single blank line; followed by a block of code that updates the text widgets

  Just try to remember to group related actions together and separate code blocks by blank lines. 
  This will also take the strain off of others reading your code, who can now focus on the actual code, not the formatting.

* `writing` isn't a noun. It's pretty confusing to use a verb as a variable name, so I recommend:

  * `writing` → `text_widget`
  * `writing1` → `text_widget1`
  * `writing2` → `text_widget2`
  * `writing3` → `text_widget3`

  In a similar manner, `update_writing` → `update_text_widgets`

* You're declaring variables in a global scope. That's a Really Bad Idea™. You would be much better off defining them in the scope of a class. As you can see, it breaks, because Python doesn't know those widgets exist.

* You've put unnecessary braces around the `T1` and `T3` assignments:

  * `T1 = (time.strftime("%H:%M:%S"))` → `T1 = time.strftime("%H:%M:%S")`
  * `T3 = (datetime.utcnow().strftime("%H:%M:%S"))` → `T3 = datetime.utcnow().strftime("%H:%M:%S")`

Guizero v0.4 changes
----------------------

* You're using the deprecated `Text.set` method. You should use the `value` property instead:

  ```python
  writing.value = "LOCAL TIME"
  writing1.value = T1
  ...
  ```

* There's the [`App.repeat`](https://github.com/lawsie/guizero/blob/version-0.4/guizero/Widget.py#L18) method, which automatically calls an object every *n* seconds.

* The `bgcolor` argument has been renamed to `bg`.

Rewrite
--------
Here's my attempt:

```python
import datetime as dt
import time

from guizero import App, Text
import pytz


class Application:
    def __init__(self, app):
        self._app = app
        self._create_widgets()
        self._app.after(200, self._update_text_widgets)

    def _create_widgets(self):
        self._text_widget = Text(self._app, text="", color="red", size=50)
        self._text_widget1 = Text(self._app, text="", color="red", size=50)
        self._text_widget2 = Text(self._app, text="T1", color="red", size=50)
        self._text_widget3 = Text(self._app, text="", color="red", size=50)

    def _update_text_widgets(self):
        t1 = time.strftime("%H:%M:%S")
        t2 = dt.datetime.utcnow().strftime("%H:%M:%S")

        self._text_widget.set("LOCAL TIME")
        self._text_widget1.set(t1)
        self._text_widget2.set("UTC")
        self._text_widget3.set(t2)

        self._app.after(200, self._update_text_widgets)


def main():
    root = App(height=1000, width=1000, bgcolor="black")
    app = Application(root)
    root.display()

if __name__ == "__main__":
    main()
```

Here's a Guizero v0.4 idiomatic version:

```python
import datetime as dt
import time

from guizero import App, Text
import pytz


class Application:
    def __init__(self, app):
        self._app = app
        self._create_widgets()
        self._app.repeat(200, self._update_text_widgets)

    def _create_widgets(self):
        self._text_widget = Text(self._app, text="", color="red", size=50)
        self._text_widget1 = Text(self._app, text="", color="red", size=50)
        self._text_widget2 = Text(self._app, text="T1", color="red", size=50)
        self._text_widget3 = Text(self._app, text="", color="red", size=50)

    def _update_text_widgets(self):
        t1 = time.strftime("%H:%M:%S")
        t2 = dt.datetime.utcnow().strftime("%H:%M:%S")

        self._text_widget.value = "LOCAL TIME"
        self._text_widget1.value = t1
        self._text_widget2.value = "UTC"
        self._text_widget3.value = t2


def main():
    root = App(height=1000, width=1000, bg="black")
    app = Application(root)
    root.display()

if __name__ == "__main__":
    main()
```

And finally, here's a version without classes, in case you're not comfortable using classes yet:

```
import datetime as dt
import time

from guizero import App, Text
import pytz


def _update_text_widgets():
    t1 = time.strftime("%H:%M:%S")
    t2 = dt.datetime.utcnow().strftime("%H:%M:%S")

    text_widget.set("LOCAL TIME")
    text_widget1.set(t1)
    text_widget2.set("UTC")
    text_widget3.set(t2)

    app.after(200, _update_text_widgets)


if __name__ == "__main__":
    app = App(height=1000, width=1000, bg="black")

    text_widget = Text(app, text="", color="red", size=50)
    text_widget1 = Text(app, text="", color="red", size=50)
    text_widget2 = Text(app, text="T1", color="red", size=50)
    text_widget3 = Text(app, text="", color="red", size=50)

    app.after(200, _update_text_widgets)
    app.display()

```

Note: you don't have to include the `if __name__ == "__main__":` statement, it's just good practice.

**Comment by James100000** [comment]
Thanks for all the input it works well.

I have learn`t a lot from that.


Thanks

**Comment by martinohanlon** [comment]
Excellent, I'm pleased @coal0 's update helped. 

The raspberry pi forum is also a really good place to get help and ideas if you need some support with your code and you'll get a much bigger audience.
