### ISSUE TITLE
Is there any way to change the background color of a Box widget?

### ISSUE THREAD

**Issue by juanlatorre** [lawsie/guizero#94]
Hi, i think the title says everything, i tried to change the background color on Box.py but i could not do it 😢 . Sorry for my bad english and thanks !

**Comment by Coal0** [comment]
Yes, this is possible.
If you are using GZ version 0.4 or later, Guizero widgets have a `tk` attribute which links to the underlying tkinter widget. Since `Box` implements the [tkinter `Frame` widget](http://effbot.org/tkinterbook/frame.htm), you can use [`Frame.configure`](http://effbot.org/tkinterbook/frame.htm#Tkinter.Frame.config-method) to customize it:

```python
import guizero as gz

app = gz.App()
box = gz.Box(app)
box.tk.configure(background="green")

# Any valid color specification can be used here, e.g.
# 'red' or '#000' or '#aabbcc'
```

Otherwise, if you are using an older GZ version, the widgets inherit directly from the underlying tkinter widget:

```
import guizero as gz

app = gz.App()
box = gz.Box(app)
box.configure(background="green")

# Note that I'm leaving out the `tk` here.

**Comment by juanlatorre** [comment]
Hi Daniel, thanks for the quick answer, i actually tried this approach but still not working. Here is my code:
```python
from extras.guizero import App, Box, Text

app = App(title="Hello world", width=1024, height=600)

box = Box(app)
box.tk.configure(background="green")

text1 = Text(box, text="Hello from the box", size=14, text_color="red", font="Arial")

app.display()
```

And the result:
![Result](https://i.imgur.com/0eaCKV6.png)

Thanks!

**Comment by Coal0** [comment]
The reason it doesn't work is because tkinter widgets automatically resize to take up as little space as possible. The `Frame` object will shrink until it fits around the `Label` object. You can migitate this by either:

* Manually setting the box's width and height.

* Overriding the background color on the `Text` object:

```python
text1.tk.configure(background="green")
```

You will have to do this for every widget created within the box, however. To avoid that, here's a quick fix:

```python
for child in box.tk.winfo_children():
    child.configure(background="green")
```

**Comment by juanlatorre** [comment]
That's it! Thank very much, you solved it !

**Comment by martinohanlon** [comment]
I have raised issue #95 to implement bg and text_color for all other widgets.
